apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-demo
  template:
    metadata:
      labels:
        app: ci-demo
    spec:
      containers:
      - name: ci-demo
        image: rabadiaf/ci-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
