apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
      - name: dummy
        image: busybox
        command: ["sleep", "3600"]
