- name: Apply Kubernetes manifest using kubectl
  shell: |
    if [ "{{ simulate | default('false') }}" == "true" ]; then
      echo "Simulating kubectl apply for CI"
      exit 0
    else
      kubectl apply --validate=false -f /app/deployment.yaml
    fi
  register: kubectl_output
  ignore_errors: false
  failed_when: kubectl_output.rc != 0
