---
- name: Deploy dummy pod to Kubernetes
  hosts: localhost
  connection: local
  tasks:
    - name: Apply Kubernetes manifest using kubectl
      shell: |
        kubectl apply --validate=false -f /app/deployment.yaml
      register: result
      failed_when: result.rc != 0
