---
- name: Simulated deployment using Ansible
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Ensure dummy file exists
      file:
        path: /tmp/deployment-successful.txt
        state: touch
