---
- name: Simulated deployment using Ansible
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure dummy file exists
      file:
        path: /tmp/deployed.txt
        state: touch

    - name: Apply Kubernetes manifest using kubectl
      shell: |
        kubectl apply --validate=false -f /app/k8s/
      register: kubectl_output
      failed_when: kubectl_output.rc != 0
      ignore_errors: false
