apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-deployments
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-default-sa
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: allow-deployments
  apiGroup: rbac.authorization.k8s.io
