name: CI/CD Dockerized Pipeline

on:
  push:
    branches: [ main ]

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull  Docker image
        run: docker pull rabadiaf/ci-demo:latest

      - name: Run container to execute deploy logic.
        run: docker run --rm rabadiaf/ci-demo:latest
