on:
  push:
    branches:
      - main

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubeconfig file
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/.kube/config

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t rabadiaf/ci-demo:latest .

      - name: Push Docker image
        run: docker push rabadiaf/ci-demo:latest

      - name: Run container to execute deploy logic
        run: docker run --rm \
          -v $HOME/.kube:/root/.kube:ro \
          rabadiaf/ci-demo:latest
