name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build -t ci-demo:${{ github.sha }} .

    # OPCIONAL: Push a Docker Hub (solo si vas a desplegar desde Kubernetes)
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Push Docker image
    #   run: |
    #     docker tag ci-demo:${{ github.sha }} youruser/ci-demo:${{ github.sha }}
    #     docker push youruser/ci-demo:${{ github.sha }}

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Simulated deployment using Ansible
      run: |
        echo '
        - name: Simulate deployment
          hosts: localhost
          connection: local
          gather_facts: false
          tasks:
            - name: Create file
              file:
                path: /tmp/deployment-successful.txt
                state: touch
        ' > deploy.yml
        ansible-playbook deploy.yml
